import { Title } from '@angular/platform-browser';

export interface Data {
    ID?: number,
    Latitud?: number,
    Longitud?: number,
    Area?: number,
    AreaUtil?: number,
    Adultos?: number,
    Niños?: number,
    Ancianos?: number,
    AdultosTrabajo?: number,
    AncianosTrabajo?: number,
    CocinaInd?: string,
    Lavadora?: string,
    Secadora?: string,
    Calefon?: string,
    PotDisp?: number,
    PotReq?: number,
    GenAnual?: number,
    ConsumoMensual?: number,
    Inversion?: number,
    LCOE?: number,
    TIR?: number,
    VAN?: number,
    TiempoRetornInv?: number,
};